apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: minesweeper-pipeline-
spec:
  pipelineRef:
    name: maven-pipeline
  serviceAccountName: pipeline
  params:
  - name: application-name
    value: microsweeper-appservice
  - name: dependency-git-url
    value: https://github.com/<YOUR-GITHUB-ID>/common-java-dependencies
  - name: application-git-url
    value: https://github.com/<YOUR-GITHUB-ID>/aro-workshop-app
  - name: dockerfile-path
    value: src/main/docker/Dockerfile.jvm
  - name: image-name
    value: <CHANGE-ME>.azurecr.io/minesweeper
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: minesweeper-source-pvc
